### ISSUE TITLE
401 Unauthorised error for Utils dependency 

### ISSUE THREAD

**Issue by bhavkaka** [bigboxer23/meural-control#113]
I am complete noob with all the terminology. I tried everything as per readme file.

On running install.sh, I get 401 unauthorised error for utils url https://maven.pkg.github.com/bigboxer23/_

I replaced it with the utils url I found in your profile but looks like the version its looking for is 2.0.15 and the new version is 2.0.16 or I might be reading that completely wrong.

I tried manually copying files under utils and now I am getting long list of java errors during test runs.

**Comment by bigboxer23** [comment]
I believe this is caused by not having your github account setup in `.m2/settings.xml` for maven.  There should be an entry added there which looks something like:

```<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository />
  <interactiveMode />
  <usePluginRegistry />
  <offline />
  <pluginGroups />
  <servers>
    <server>
      <id>github</id>
      <username>bigboxer23</username>
      <password>xxx_xxxxxxxxxxxxxxxxx</password>
    </server>
  </servers>
  <mirrors />
  <proxies />
</settings>
```

where username is your own, and password is a github access token created for your account (`settings` -> `developer settings` -> `tokens classic`).
